version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

#  postgresql:
#   container_name: postgres_db
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: app
#      POSTGRES_USER: app
#      POSTGRES_PASSWORD: pass
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
#      interval: 5s
#      timeout: 5s
#     retries: 5

  gate-simulator:
    build:
      context: ./gate-simulator
      dockerfile: Dockerfile
    container_name: gate_simulator
    ports:
      - "9999:9999"
    # Для запуска npm start из package.json
    command: npm start
    # Если Dockerfile не используется, а запускается напрямую npm start, то можно так:
    # image: node:16-alpine
    # working_dir: /app
    # volumes:
    #   - ./gate-simulator:/app
    # command: npm start
